import React from 'react';

import { Theme } from '@radix-ui/themes';
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.scss';
import { ThemeProvider } from 'next-themes';

import 'animation-library-test-abdullah-altun';
import { AuthProvider } from '@/context/AuthProvider';
import { ToastProvider, ToastViewport } from '@/context/ToastContext';

import '@radix-ui/themes/styles.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Animation Playground',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <ToastProvider>
            <ThemeProvider attribute={'class'} defaultTheme={'system'}>
              <Theme appearance="inherit" radius="large" accentColor={'indigo'}>
                {children}
                <SpeedInsights />
                <Analytics />
                <ToastViewport />
              </Theme>
            </ThemeProvider>
          </ToastProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
